routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


Route::namespace('forum')->group(function () {
    Route::get('forum/filter', 'FilterController@index');

    Route::get('forum/search', 'SearchController@index')->name('threads.search');

    Route::get('forum/tags', 'TagController@index');
    Route::get('forum/{tag}', 'TagController@show')->name('tags.show');

    Route::get('forum', 'ThreadController@index')->name('threads');
    Route::get('create-new-thread', 'ThreadController@create')->name('threads.create');
    Route::post('create-new-thread', 'ThreadController@store')->name('threads.store');
    Route::get('forum/{tag}/{thread}', 'ThreadController@show')->name('threads.show');
    Route::get('forum/{tag}/{thread}/edit', 'ThreadController@edit')->name('threads.edit');
    Route::patch('forum/{tag}/{thread}/edit', 'ThreadController@update');
    Route::delete('forum/{tag}/{thread}', 'ThreadController@destroy')->name('threads.delete');

    Route::post('reply-on-the-thread/{thread}', 'ReplyController@store')->name('replies.store');
    Route::get('edit-reply-on-the-thread/{thread}/{reply}', 'ReplyController@edit')->name('replies.edit');
    Route::patch('edit-reply-on-the-thread/{thread}/{reply}', 'ReplyController@update');

    Route::patch('mark-as-answer-at-reply/{reply}', 'AnswerController@store')->name('answer.create');
});

Route::get('{user}', 'UserController@show')->name('users.show');
Route::get('account/profile', 'UserController@edit')->name('users.edit');
Route::patch('account/profile', 'UserController@update');

app/User.php
<?php

namespace App;

use App\Models\Forum\Reply;
use App\Models\Forum\Thread;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username', 'hash', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function threads()
    {
        return $this->hasMany(Thread::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function usernameOrHash()
    {
        return $this->username ?? $this->hash;
    }

    public function avatar($size = 200)
    {
        if (!$this->avatar) {
            return "https://www.gravatar.com/avatar/" . md5(strtolower(trim($this->email))) . "?d=mm&s=" . $size;
        } else {
            return 'storage/' . $this->avatar;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('show');
    }

    public function show($user)
    {
        $user = User::withCount('threads')->whereHash($user)->orWhere('username', $user)->firstOrFail();
        $threads = $user->threads()->latest()->simplePaginate(5);
        return view('users.show', compact('user', 'threads'));
    }

    public function edit()
    {
        return view('users.edit');
    }

    public function update()
    {
        $avatar = request()->file('avatar');
        $avatar_validate = ['image', 'mimes:jpeg,png,jpg,svg', 'max:2048'];

        request()->validate([
            'username' => ['required', 'alpha_num', 'max:20', 'min:3', 'unique:users,username,' . auth()->id()],
            'name' => ['required', 'string'],
            'avatar' => $avatar ? $avatar_validate : '',
        ]);

        $hash = auth()->user()->hash;
        $avatar_name = $avatar->storeAs('profile-picture', "{$hash}.{$avatar->extension()}");

        auth()->user()->update([
            'username' => request('username'),
            'name' => request('name'),
            'avatar' => $avatar_name,
        ]);

        return back();
    }
}

resources/views/users/edit.blade.php
@extends('layouts.partials.auth')

@section('title', 'Edit Profiles')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit profile</div>
                <div class="card-body">
                    <form action="{{ route('users.edit') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')
                        <div class="d-flex mb-2">
                            <img width="100" height="100" src="{{ asset(auth()->user()->avatar()) }}" class="rounded-circle mr-3" style="object-fit: cover; object-position: center;" alt="...">
                            <div class="form-group align-items-center d-flex">
                                <div>
                                    <label for="avatar">Upload avatar</label>
                                    <input type="file" name="avatar" id="avatar" class="form-control-file">
                                    @error('avatar')
                                        <small class="text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" name="username" id="username" class="form-control" placeholder="@johndoe" value="{{ old('username') ?? auth()->user()->username }}">
                            @error('username')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="name">Full name</label>
                            <input type="text" name="name" id="name" class="form-control" value="{{ old('name') ?? auth()->user()->name }}">
                            @error('name')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('title', $user->name )

@section('content')
<div class="card mb-3">
    <div class="card-body">
        <div class="media mb-2">
            <img width="50" height="50" src="{{ $user->avatar() }}" class="rounded-circle mr-3" style="object-fit: cover; object-position: center;" alt="...">
            <div class="media-body">
                <div class="mt-0 d-block">{{ $user->name }}</div>
                <div class="text-secondary">
                    Threads : {{ $user->threads_count }}
                </div>
                <div class="text-secondary">
                    Joined : {{ $user->created_at->format('d F, Y') }}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header">
        <a href="{{ route('threads') }}" class="text-secondary">Forum</a> @isset( $tag )
            / {{ $tag->name }}
        @endisset
    </div>

    <div class="card-body">
        @foreach ($threads as $thread)
        <div class="media mb-2">
            <div class="media-body">
                <a href="{{ route('threads.show', [$thread->tag, $thread]) }}" class="mt-0 d-block">{{ $thread->title }}</a>
                <small>in <a href="{{ route('tags.show', $thread->tag) }}">{{ $thread->tag->name }}</a></small>
                <div class="text-secondary">
                    {{ Str::limit($thread->body, 170) }}
                </div>
                <small class="text-secondary">
                    <a href="{{ route('users.show', $thread->author) }}" class="text-secondary">{{ $thread->author->name }}</a> posted {{ $thread->created_at->diffForHumans() }} &middot; {{ $thread->replies_count }} {{ Str::plural('reply', $thread->replies_count) }}
                </small>
            </div>
        </div>
        <hr>
        @endforeach
    </div>
</div>

<div class="mt-3 justify-content-center">
    {{ $threads->links() }}
</div>

@endsection